### PR TITLE
Disable global barrier check in m2l preprocess

### PR DESCRIPTION
**Pull request by inducer**
Here's another one similar to #132.

cc @isuruf @alexfikl

### CODE REVIEW

**Comment by inducer** [comment]
cc @rkirby

**Comment by isuruf** [comment]
https://github.com/inducer/sumpy/pull/131 is an alternative to this.

**Comment by alexfikl** [comment]
Can confirm that #131 also does a nice job at fixing this issue!
```
133:	elapsed: 427.10s wall 0.98x CPU
131: 	elapsed: 372.73s wall 1.04x CPU
```
(this is just one run on `dunkel` using https://github.com/inducer/sumpy/issues/129#issuecomment-1207257972, so not rigorous, but still)

**Comment by inducer** [comment]
Sounds good. Let's go with #131 instead.

**Pull request closed without merging**
