### PR TITLE
Misc modernize (pyupgrade)

### PR DESCRIPTION
**Pull request by alexfikl**
Noticed in #98 that there were still places that weren't using new-style `super()`, so ran `pyupgrade` over everything (again?). 

The commits are nicer to look at separately.

### CODE REVIEW

**Comment by inducer** [comment]
Thanks for this! @isuruf has a bunch of PRs pending against sumpy, and I feel like this might cause a healthy dose of conflicts. @isuruf, how do you feel about this?

**Comment by alexfikl** [comment]
> Thanks for this! @isuruf has a bunch of PRs pending against sumpy, and I feel like this might cause a healthy dose of conflicts. @isuruf, how do you feel about this?

I'm fine with letting this wait and merging later!

**Comment by isuruf** [comment]
Thanks. Let's wait until we get #95 in and I can rebase this. What were the options used for pyupgrade so that I can run this myself?

**Comment by alexfikl** [comment]
> Thanks. Let's wait until we get #95 in and I can rebase this.

Sounds good!

> What were the options used for pyupgrade so that I can run this myself?

It's just `pyupgrade --py36-plus`, so something like
```
find . -name "*.py" -exec pyupgrade --py36-plus {} \;
```

It's very conservative with the f-strings, so the large majority of those in adf469f are done by hand.

**Comment by alexfikl** [comment]
@inducer Rebased this on `main` and fixed the conflicts, so it should be good for a look now.

**Review by isuruf — APPROVED** [review]

**Comment by inducer** [comment]
Thanks!

**Pull request merged**
